export const MOVING_COMP = 'MOVING_COMP';
export const PLAYER_CONTROLLED_COMP = 'PLAYER_CONTROLLED_COMP';
export const BACKGROUND_COMP = 'BACKGROUND_COMP';
export const MOVEMENT_COMP = 'MOVEMENT_COMP';
export const TRAVERSABLE_COMP = 'TRAVERSABLE_COMP';
export const POSITION_COMP = 'POSITION_COMP';
export const UI_COMP = 'UI_COMP';
